#include "internal/zopfli/src/zopfli/blocksplitter.c"
#include "internal/zopfli/src/zopfli/cache.c"
#include "internal/zopfli/src/zopfli/deflate.c"
#include "internal/zopfli/src/zopfli/gzip_container.c"
#include "internal/zopfli/src/zopfli/hash.c"
#include "internal/zopfli/src/zopfli/katajainen.c"
#include "internal/zopfli/src/zopfli/lz77.c"
#include "internal/zopfli/src/zopfli/squeeze.c"
#include "internal/zopfli/src/zopfli/symbols.h"
#include "internal/zopfli/src/zopfli/tree.c"
#include "internal/zopfli/src/zopfli/util.c"
#include "internal/zopfli/src/zopfli/zlib_container.c"
#include "internal/zopfli/src/zopfli/zopfli_lib.c"

#include "internal/bridge_zopflipng.c"